---
- hosts: all

  tasks:
  - name: create user
    user:
       name: user
       shell: /bin/bash
       groups: sudo,admin,user
       password: changeme
       append: yes

    - name: Disable user's password
      shell:
         cmd: passwd -d user
    - name: Expire user's password
      shell:
         cmd: passwd -e user
